### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by arunpatala** [arunpatala/captcha.irctc#3]

**Comment by mrgloom** [comment]
Hello, can you provide link/example how to create demo app on AWS like yours? I need this for some computer vision / machine learning demos.

**Comment by arunpatala** [comment]
Hey sure I can help if you find any difficulty. If you need any particular help ping me at arunpatala@gmail.com

I was using AWS free instance using ubuntu/nodejs/express. 
Here is a broad overview of steps to take. You can google them and find many tutorials of each step.
1. Create aws account (need credit information but there are some free instances)
2. Create EC2 instance (I used ubuntu 64 bit linux)
3. Create Key pair for logging into the system (ssh -i ubuntu.pem ubuntu@ip-address)
4. Create public dns for your instance
5. Install nodejs and express
6. install other computer vision tools (like torch)
7. use nodejs to create webserver
8. use multer module for posting image

**Comment by arunpatala** [comment]
Dont forget to open port 80 after installing webserver
